export const tokens = [
    {
      name: 'Ethereum',
      symbol: 'ETH',
      icon: 'Ξ',
      category: ['all', 'popular'],
      lockCount: '50K',
      totalLocked: '$500M',
      minLockPeriod: '1 hour',
      maxLockPeriod: '10 years',
      networkFee: '0.01 ETH',
      riskLevel: 'Medium',
      marketCap: '$300B',
      supported: true,
    },
    {
      name: 'USDT',
      symbol: 'USDT',
      icon: '💵',
      category: ['all', 'stablecoins'],
      lockCount: '10K',
      totalLocked: '$200M',
      minLockPeriod: '1 hour',
      maxLockPeriod: '2 years',
      networkFee: '0.5 USDT',
      riskLevel: 'Low',
      marketCap: '$83B',
      supported: true,
    },
    {
      name: 'DAI',
      symbol: 'DAI',
      icon: '🪙',
      category: ['all', 'stablecoins'],
      lockCount: '8K',
      totalLocked: '$150M',
      minLockPeriod: '30 minutes',
      maxLockPeriod: '3 years',
      networkFee: '0.3 DAI',
      riskLevel: 'Low',
      marketCap: '$6B',
      supported: true,
    },
    {
      name: 'USDC',
      symbol: 'USDC',
      icon: '💰',
      category: ['all', 'stablecoins'],
      lockCount: '12K',
      totalLocked: '$180M',
      minLockPeriod: '1 hour',
      maxLockPeriod: '5 years',
      networkFee: '0.4 USDC',
      riskLevel: 'Low',
      marketCap: '$26B',
      supported: true,
    },
    {
      name: 'TUSD',
      symbol: 'TUSD',
      icon: '🔵',
      category: ['all', 'stablecoins'],
      lockCount: '7K',
      totalLocked: '$100M',
      minLockPeriod: '1 hour',
      maxLockPeriod: '3 years',
      networkFee: '0.3 TUSD',
      riskLevel: 'Low',
      marketCap: '$4B',
      supported: true,
    },
    {
      name: 'UNI',
      symbol: 'UNI',
      icon: '🦄',
      category: ['all', 'defi'],
      lockCount: '5K',
      totalLocked: '$100M',
      minLockPeriod: '1 hour',
      maxLockPeriod: '4 years',
      networkFee: '0.01 UNI',
      riskLevel: 'Medium',
      marketCap: '$5B',
      supported: true,
    },
    {
      name: 'AAVE',
      symbol: 'AAVE',
      icon: '🏦',
      category: ['all', 'defi'],
      lockCount: '3K',
      totalLocked: '$80M',
      minLockPeriod: '1 day',
      maxLockPeriod: '3 years',
      networkFee: '0.02 AAVE',
      riskLevel: 'Medium',
      marketCap: '$1B',
      supported: true,
    },
    {
      name: 'COMP',
      symbol: 'COMP',
      icon: '⚙️',
      category: ['all', 'defi'],
      lockCount: '2K',
      totalLocked: '$60M',
      minLockPeriod: '6 hours',
      maxLockPeriod: '3 years',
      networkFee: '0.01 COMP',
      riskLevel: 'Medium',
      marketCap: '$500M',
      supported: true,
    },
    {
      name: 'SUSHI',
      symbol: 'SUSHI',
      icon: '🍣',
      category: ['all', 'defi'],
      lockCount: '4K',
      totalLocked: '$70M',
      minLockPeriod: '12 hours',
      maxLockPeriod: '2 years',
      networkFee: '0.05 SUSHI',
      riskLevel: 'Medium',
      marketCap: '$500M',
      supported: true,
    },
    {
      name: 'SHIBA INU',
      symbol: 'SHIB',
      icon: '🐶',
      category: ['all', 'meme'],
      lockCount: '100K',
      totalLocked: '$50M',
      minLockPeriod: '30 minutes',
      maxLockPeriod: '1 year',
      networkFee: '1M SHIB',
      riskLevel: 'High',
      marketCap: '$7B',
      supported: true,
    },
    {
      name: 'DOGECOIN',
      symbol: 'DOGE',
      icon: '🐕',
      category: ['all', 'meme'],
      lockCount: '80K',
      totalLocked: '$40M',
      minLockPeriod: '1 hour',
      maxLockPeriod: '2 years',
      networkFee: '10 DOGE',
      riskLevel: 'High',
      marketCap: '$10B',
      supported: true,
    },
    {
      name: 'PEPE',
      symbol: 'PEPE',
      icon: '🐸',
      category: ['all', 'meme'],
      lockCount: '60K',
      totalLocked: '$25M',
      minLockPeriod: '10 minutes',
      maxLockPeriod: '1 year',
      networkFee: '0.01 PEPE',
      riskLevel: 'High',
      marketCap: '$500M',
      supported: true,
    },
    {
      name: 'FLOKI',
      symbol: 'FLOKI',
      icon: '🐕‍🦺',
      category: ['all', 'meme'],
      lockCount: '50K',
      totalLocked: '$30M',
      minLockPeriod: '1 hour',
      maxLockPeriod: '1 year',
      networkFee: '500K FLOKI',
      riskLevel: 'High',
      marketCap: '$350M',
      supported: true,
    },
  ];
  
export const categories = [
    { id: 'all', name: 'All', count: tokens.length },
    { id: 'stablecoins', name: 'Stablecoins', count: tokens.filter(t => t.category.includes('stablecoins')).length },
    { id: 'defi', name: 'DeFi Tokens', count: tokens.filter(t => t.category.includes('defi')).length },
    { id: 'meme', name: 'Meme Tokens', count: tokens.filter(t => t.category.includes('popular')).length }
];

  export const faqs = [
    {
      question: "How does FVKRY PRVNTA work?",
      answer: "Our platform allows you to lock your crypto assets for a specified period, helping you achieve your savings goals while earning rewards."
    },
    {
      question: "Is it safe to lock my assets?",
      answer: "Yes, our smart contracts are audited by leading security firms and we implement industry best practices for asset security."
    },
    {
      question: "What are the fees?",
      answer: "We charge a minimal 0.3% fee only upon withdrawal to maintain platform sustainability and development."
    },
    {
      question: "Can I withdraw early?",
      answer: "Early withdrawals are possible in emergency situations, subject to a higher fee to discourage premature withdrawals."
    }
  ];